version: '3.8'

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - 8080:8080
    restart: always

  graphrag-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - LLM_TYPE=${LLM_TYPE:-ollama}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    restart: unless-stopped